# Generated by Django 3.0.4 on 2021-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('maths', models.PositiveSmallIntegerField()),
                ('physics', models.PositiveSmallIntegerField()),
                ('chemistry', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
