# Generated by Django 3.0.4 on 2021-01-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='total',
        ),
    ]
