# Generated by Django 3.0.4 on 2021-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_marks', '0002_auto_20210106_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
